25095-newgreenfields
DFE-Digital/spi-models pull request #16
Opened 2020-02-12 14:49 UTC by mmiddleton3301

2020-02-12 14:56 UTC, simonbu11 requested changes

2020-02-12 14:56 UTC, simonbu11 commented on src/Dfe.Spi.Models/Dfe.Spi.Models/LearningProvider.cs
> +        public string RegionalSchoolsCommisionerRegion { get; set; }
Typo - Commissioner not Commisioner

2020-02-13 09:05 UTC, mmiddleton3301 commented on src/Dfe.Spi.Models/Dfe.Spi.Models/LearningProvider.cs
> +        public string RegionalSchoolsCommisionerRegion { get; set; }
Good spot! 👀

2020-02-13 09:12 UTC, simonbu11 approved these changes

2020-02-13 09:12 UTC, merged